export const ANALYTICS_EVENTS = {
  PRODUCT_VIEW: "PRODUCT_VIEW",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",

  SESSION_START: "SESSION_START",
  SESSION_END: "SESSION_END",

  PRODUCT_SEARCH: "PRODUCT_SEARCH",
  PRODUCT_FILTER: "PRODUCT_FILTER",
  PRODUCT_SORT: "PRODUCT_SORT",

  COUPON_APPLIED: "COUPON_APPLIED",
  COUPON_FAILED: "COUPON_FAILED",

  CHECKOUT_STARTED: "CHECKOUT_STARTED",
  PAYMENT_INITIATED: "PAYMENT_INITIATED",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  PAYMENT_FAILED: "PAYMENT_FAILED",
} as const;
