import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel  } from "@radix-ui/themes";
import { Provider,useAtom } from "jotai";
import { myStore, themeColor } from "./store/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      
        <Theme 
          accentColor="crimson" 
          grayColor="sand" 
          radius="large" 
          scaling="95%"
          appearance="dark">
            <Provider store={myStore}>
              <main>
                {children}
              </main>
            </Provider>
            
          
        </Theme>
        
      </body>
    </html>
  );
}
